export const mappings = [
  {
    // If the studio contains known separators, or is PascalCase or camelCase,
    // all of its parts have to match
    studios: [
      "My Studio",
      "My studio",
      "my Studio",
      "my studio",
      "MyStudio",
      "myStudio",
      "my_studio",
      "my-studio",
    ],
    does_match: [
      "my studio",
      "my_studio",
      "my-studio",
      "MyStudio",
      "myStudio",
      "my   studio",
      "again my   studio",
      "my studio thumbnail",
      "MyStudio thumbnail",
      "myStudio thumbnail",
      "myStudio-thumbnail",
      "my studio-thumbnail",
      "my studio_thumbnail",
      "MyStudio_thumbnail",
      "myStudio -thumbnail",
    ],
    non_match: [
      "Mystudio",
      "MysTudio",
      "m ystudio",
      "mys tudio",
      "amy studio",
      "amystudio",
      "  mystudio",
      "-mystudio",
      "mystudio thumbnail",
      "mystudio-thumbnail",
      "mystudio_thumbnail",
    ],
  },
  {
    studios: ["Studio"],
    does_match: [
      "my studio",
      "my_studio",
      "my-studio",
      "my   studio",
      "some studio thumbnail",
      "amy studio",
      "  studio",
      "-studio",
      "studio thumbnail",
      "studio-thumbnail",
      "studio_thumbnail",
    ],
    non_match: [
      "MyStudio",
      "myStudio",
      "Mystudio",
      "basicStudio thumbnail",
      "anotherStudio thumbnail",
      "MysTudio",
      "m ystudio",
      "mys tudio",
      "amystudio",
      "  mystudio",
      "-mystudio",
      "mystudio thumbnail",
      "mystudio-thumbnail",
      "mystudio_thumbnail",
    ],
  },
  {
    studios: [
      // lowercase should only match a full word occurrence, since we don't know where to split
      "mystudio",
      "Mystudio",
    ],
    does_match: [
      "Mystudio",
      "mystudio",
      "___mystudio",
      "  mystudio",
      "-mystudio",
      "mystudio thumbnail",
      "mystudio-thumbnail",
      "mystudio_thumbnail",
    ],
    non_match: [
      "MyStudio thumbnail",
      "myStudio thumbnail",
      "MyStudio",
      "MysTudio",
      "my studio",
      "my_studio",
      "my-studio",
      "my   studio",
      "my studio thumbnail",
      "m ystudio",
      "mys tudio",
      "amy studio",
      "amystudio",
    ],
  },
  {
    studios: [
      "MultiWord studio",
      "MultiWord Studio",
      "multiWord studio",
      "multiWord Studio",
      "multi-word-studio",
      "multi-word studio",
    ],
    does_match: [
      "my multi word studio",
      "my multi word Studio",
      "my multiWord studio",
      "my multiWord Studio",
      "my MultiWord studio",
      "my MultiWord Studio",
      "my__multi_word_studio",
      "my-multi-word-studio",
      "MultiWord Studio",
      "multiWord studio",
      "my  multi word   studio",
    ],
    non_match: [
      "multiword studio",
      "multiword studiotwo",
      "multiword studioTwo",
      "multiWord StudioTwo",
      "MultiWord StudioTwo",
      "my multi word studiotwo",
      "my multi word studioTwo",
      "my multi word Studiotwo",
      "my multi word StudioTwo",
      "my MultiWord Studiotwo",
      "my MultiWord StudioTwo",
      "mymultiword studio",
      "MyMultiWord studio",
      "myMultiWord studio",
      "again myMultiWord studio",
      " multi word   my    studio",
      "again multi word  my   studio",
    ],
  },
];
