export const fullWordMatchFixtures = [
  {
    // If the studio contains known separators, or is PascalCase or camelCase,
    // all of its parts have to match
    inputs: [
      "My Studio",
      "My studio",
      "my Studio",
      "my studio",
      "MyStudio",
      "myStudio",
      "my_studio",
      "my-studio",
    ],
    compare_does_match: [
      "my studio",
      "my_studio",
      "my-studio",
      "MyStudio",
      "myStudio",
      "my   studio",
      "again my   studio",
      "my studio thumbnail",
      "MyStudio thumbnail",
      "myStudio thumbnail",
      "myStudio-thumbnail",
      "MyStudio_thumbnail",
      "myStudio -thumbnail",
    ],
    compare_non_match: [
      "Mystudio",
      "MysTudio",
      "m ystudio",
      "mys tudio",
      "amy studio",
      "amystudio",
      "  mystudio",
      "-mystudio",
      "mystudio thumbnail",
      "mystudio-thumbnail",
      "mystudio_thumbnail",
      "my studio-thumbnail", // would be allowed with non strict word matching
      "my studio_thumbnail", // would be allowed with non strict word matching
    ],
  },
  {
    inputs: ["Studio"],
    compare_does_match: [
      "my studio",
      "my_studio",
      "my-studio",
      "my   studio",
      "some studio thumbnail",
      "amy studio",
      "  studio",
      "-studio",
      "studio thumbnail",
      "studio-thumbnail",
      "studio_thumbnail",
    ],
    compare_non_match: [
      "MyStudio",
      "myStudio",
      "Mystudio",
      "basicStudio thumbnail",
      "anotherStudio thumbnail",
      "MysTudio",
      "m ystudio",
      "mys tudio",
      "amystudio",
      "  mystudio",
      "-mystudio",
      "mystudio thumbnail",
      "mystudio-thumbnail",
      "mystudio_thumbnail",
    ],
  },
  {
    inputs: [
      // lowercase should only match a full word occurrence, since we don't know where to split
      "mystudio",
      "Mystudio",
    ],
    compare_does_match: [
      "Mystudio",
      "mystudio",
      "___mystudio",
      "  mystudio",
      "-mystudio",
      "mystudio thumbnail",
      "mystudio-thumbnail",
      "mystudio_thumbnail",
    ],
    compare_non_match: [
      "MyStudio thumbnail",
      "myStudio thumbnail",
      "MyStudio",
      "MysTudio",
      "my studio",
      "my_studio",
      "my-studio",
      "my   studio",
      "my studio thumbnail",
      "m ystudio",
      "mys tudio",
      "amy studio",
      "amystudio",
    ],
  },
  {
    inputs: ["MultiWord studio", "MultiWord Studio", "multiWord studio", "multiWord Studio"],
    compare_does_match: [
      "my multi word studio",
      "my multi word Studio",
      "my multiWord studio",
      "my multiWord Studio",
      "my MultiWord studio",
      "my MultiWord Studio",
      "my__multi_word_studio",
      "my-multi-word-studio",
      "MultiWord Studio",
      "multiWord studio",
      "my  multi word   studio",
    ],
    compare_non_match: [
      "multiword studio",
      "multiword studiotwo",
      "multiword studioTwo",
      "multiWord StudioTwo",
      "MultiWord StudioTwo",
      "my multi word studiotwo",
      "my multi word studioTwo",
      "my multi word Studiotwo",
      "my multi word StudioTwo",
      "my MultiWord Studiotwo",
      "my MultiWord StudioTwo",
      "mymultiword studio",
      "MyMultiWord studio",
      "myMultiWord studio",
      "again myMultiWord studio",
      " multi word   my    studio",
      "again multi word  my   studio",
    ],
  },
  {
    inputs: ["multi-word-studio"],
    compare_does_match: [
      "my multi word studio",
      "my multi word Studio",
      "my__multi_word_studio",
      "my-multi-word-studio",
      "my  multi word   studio",
    ],
    compare_non_match: [
      "multiword studio",
      "multiword studiotwo",
      "multiword studioTwo",
      "multiWord StudioTwo",
      "MultiWord StudioTwo",
      "my multi word studiotwo",
      "my multi word studioTwo",
      "my multi word Studiotwo",
      "my multi word StudioTwo",
      "my MultiWord Studiotwo",
      "my MultiWord StudioTwo",
      "mymultiword studio",
      "MyMultiWord studio",
      "myMultiWord studio",
      "again myMultiWord studio",
      " multi word   my    studio",
      "again multi word  my   studio",
      // would be allowed with non strict word matching
      "my multiWord studio",
      "my multiWord Studio",
      "my MultiWord studio",
      "my MultiWord Studio",
      "MultiWord Studio",
      "multiWord studio",
    ],
  },
  {
    options: {
      flattenWordGroups: true,
    },
    inputs: ["multi-word-studio"],
    compare_does_match: [
      "my multi word studio",
      "my multi word Studio",
      "my__multi_word_studio",
      "my-multi-word-studio",
      "my  multi word   studio",
      "my multiWord studio",
      "my multiWord Studio",
      "my MultiWord studio",
      "my MultiWord Studio",
      "MultiWord Studio",
      "multiWord studio",
      // allowed because of non strict word matching
      "multiWord StudioTwo",
      "MultiWord StudioTwo",
      "my multi word studioTwo",
      "my multi word StudioTwo",
      "my MultiWord StudioTwo",
      "MyMultiWord studio",
      "myMultiWord studio",
      "again myMultiWord studio",
    ],
    compare_non_match: [
      // lowercase words still cannot be split
      "multiword studio",
      "multiword studiotwo",
      "multiword studioTwo",
      "my multi word studiotwo",
      "my multi word Studiotwo",
      "my MultiWord Studiotwo",
      "mymultiword studio",
      " multi word   my    studio",
      "again multi word  my   studio",
    ],
  },
].map((fixture) => ({
  options: fixture.options,
  inputs: fixture.inputs,
  compare_does_match: {
    compareStrings: fixture.compare_does_match,
    expected: fixture.inputs,
  },
  compare_non_match: {
    compareStrings: fixture.compare_non_match,
    expected: [],
  },
}));
