#!/usr/bin/with-contenv bash

# We want a configuration file in /config so it can be stored in a persistent volume and not wiped out if we update the container.
if [ ! -f /config/config.json ] && [ ! -f /config/config.yaml ]
then
	echo "copying example configuration to /config/config.json"
	cp config.example.json /config/config.json
fi

if [ ! -d /videos ]
then
	mkdir /videos
fi
if [ ! -d /images ]
then
	mkdir /images
fi

# check Library permissions
PUID=${PUID:-911}
if [ ! "$(stat -c %u /config/library)" = "$PUID" ]; then
	echo "Change in ownership detected, please be patient while we chown existing files"
	echo "This could take some time"
	chown abc:abc -R \
	/config/library
fi

# set permissions non-recursively on config folders
chown abc:abc /config /config/*